version: '3.8'

services:
  bot:
    build: .
    container_name: discord-fun-bot
    restart: unless-stopped
    ports:
      - "8736:8736"  # Map custom port
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8736/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: discord-bot-network